MODEL_REGISTRY = {
    "wan-t2v-1.3b": {
        "name": "Wan2.1 Text-to-Video 1.3B",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Wan-AI/Wan2.1-T2V-1.3B-Diffusers",
        "size_gb": 5.2,
        "vram_min_gb": 4,
        "vram_recommended_gb": 8,
        "runner_class": "inference.video.wan.WanT2VRunner",
        "description": "Fast open-source text-to-video model. Generates 5s clips at 480p."
    },
    "wan-t2v-1.3b-fp8": {
        "name": "Wan2.1 Text-to-Video 1.3B FP8 Quantized",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Wan-AI/Wan2.1-T2V-1.3B-FP8",
        "size_gb": 2.6,
        "vram_min_gb": 3,
        "vram_recommended_gb": 4,
        "runner_class": "inference.video.wan.WanT2VRunner",
        "description": "Ultra low-VRAM 4GB optimized Wan2.1 text-to-video model."
    },
    "wan-t2v-14b": {
        "name": "Wan2.1 Text-to-Video 14B High Quality",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Wan-AI/Wan2.1-T2V-14B-Diffusers",
        "size_gb": 28.0,
        "vram_min_gb": 12,
        "vram_recommended_gb": 24,
        "runner_class": "inference.video.wan.WanT2VRunner",
        "description": "Cinematic quality 720p/1080p text-to-video generation."
    },
    "wan-i2v-1.3b": {
        "name": "Wan2.1 Image-to-Video 1.3B",
        "category": "video",
        "subcategory": "image-to-video",
        "hf_repo": "Wan-AI/Wan2.1-I2V-480p-1.3B-Diffusers",
        "size_gb": 5.2,
        "vram_min_gb": 4,
        "vram_recommended_gb": 8,
        "runner_class": "inference.video.wan.WanI2VRunner",
        "description": "Animate still images into video. 480p, 5s clips."
    },
    "hunyuan-video": {
        "name": "HunyuanVideo 13B",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "tencent/HunyuanVideo",
        "size_gb": 26.5,
        "vram_min_gb": 12,
        "vram_recommended_gb": 24,
        "runner_class": "inference.video.hunyuan.HunyuanVideoRunner",
        "description": "State of the art open source video generation model by Tencent."
    },
    "flux-schnell": {
        "name": "FLUX.1 Schnell",
        "category": "image",
        "subcategory": "text-to-image",
        "hf_repo": "black-forest-labs/FLUX.1-schnell",
        "size_gb": 23.8,
        "vram_min_gb": 8,
        "vram_recommended_gb": 16,
        "runner_class": "inference.image.flux.FluxSchnellRunner",
        "description": "Fast, high-quality image generation. 1-4 steps."
    },
    "flux-schnell-fp8": {
        "name": "FLUX.1 Schnell FP8 Quantized",
        "category": "image",
        "subcategory": "text-to-image",
        "hf_repo": "city96/FLUX.1-schnell-gguf",
        "size_gb": 6.4,
        "vram_min_gb": 4,
        "vram_recommended_gb": 8,
        "runner_class": "inference.image.flux.FluxSchnellRunner",
        "description": "Low-VRAM 4GB-8GB quantized FLUX image model."
    },
    "flux-dev": {
        "name": "FLUX.1 Dev",
        "category": "image",
        "subcategory": "text-to-image",
        "hf_repo": "black-forest-labs/FLUX.1-dev",
        "size_gb": 23.8,
        "vram_min_gb": 12,
        "vram_recommended_gb": 24,
        "runner_class": "inference.image.flux.FluxDevRunner",
        "description": "Ultra high-fidelity non-commercial image generation model."
    },
    "kokoro-tts": {
        "name": "Kokoro TTS 82M",
        "category": "audio",
        "subcategory": "text-to-speech",
        "hf_repo": "hexgrad/Kokoro-82M",
        "size_gb": 0.3,
        "vram_min_gb": 0,
        "vram_recommended_gb": 0,
        "runner_class": "inference.audio.kokoro_tts.KokoroTTSRunner",
        "description": "Lightweight TTS. Runs on CPU. Apache 2.0 license."
    },
    "cosyvoice-tts": {
        "name": "CosyVoice 300M",
        "category": "audio",
        "subcategory": "text-to-speech",
        "hf_repo": "FunAudioLLM/CosyVoice-300M",
        "size_gb": 1.2,
        "vram_min_gb": 2,
        "vram_recommended_gb": 4,
        "runner_class": "inference.audio.cosyvoice.CosyVoiceRunner",
        "description": "Expressive multilingual speech synthesis with emotion control."
    },
    "chatterbox": {
        "name": "Chatterbox Voice Clone",
        "category": "audio",
        "subcategory": "voice-clone",
        "hf_repo": "resemble-ai/chatterbox",
        "size_gb": 1.5,
        "vram_min_gb": 4,
        "vram_recommended_gb": 6,
        "runner_class": "inference.audio.chatterbox_vc.ChatterboxRunner",
        "description": "Zero-shot voice cloning. MIT license. Near-commercial quality."
    },
    "wav2lip": {
        "name": "Wav2Lip Standard",
        "category": "video",
        "subcategory": "lip-sync",
        "hf_repo": "wav2lip/wav2lip",
        "size_gb": 0.4,
        "vram_min_gb": 2,
        "vram_recommended_gb": 4,
        "runner_class": "inference.video.lipsync.Wav2LipRunner",
        "description": "Industry standard lip sync. Audio + video -> synced video."
    },
    "wav2lip-gan": {
        "name": "Wav2Lip GAN High Fidelity",
        "category": "video",
        "subcategory": "lip-sync",
        "hf_repo": "wav2lip/wav2lip-gan",
        "size_gb": 0.4,
        "vram_min_gb": 2,
        "vram_recommended_gb": 4,
        "runner_class": "inference.video.lipsync.Wav2LipGANRunner",
        "description": "High-fidelity lip sync with visual GAN discriminator for sharp mouth details."
    },
    "whisper-base": {
        "name": "OpenAI Whisper Base",
        "category": "audio",
        "subcategory": "speech-to-text",
        "hf_repo": "openai/whisper-base",
        "size_gb": 0.5,
        "vram_min_gb": 1,
        "vram_recommended_gb": 2,
        "runner_class": "inference.audio.whisper_stt.WhisperRunner",
        "description": "Fast automatic speech recognition and timestamped subtitle captioning."
    },
    "whisper-large-v3-turbo": {
        "name": "OpenAI Whisper Large v3 Turbo",
        "category": "audio",
        "subcategory": "speech-to-text",
        "hf_repo": "openai/whisper-large-v3-turbo",
        "size_gb": 1.6,
        "vram_min_gb": 2,
        "vram_recommended_gb": 4,
        "runner_class": "inference.audio.whisper_stt.WhisperRunner",
        "description": "Fast, state-of-the-art multilingual speech recognition."
    },
    "ltx-video": {
        "name": "Lightricks LTX Video",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Lightricks/LTX-Video",
        "size_gb": 8.5,
        "vram_min_gb": 8,
        "vram_recommended_gb": 16,
        "runner_class": "inference.video.ltx.LTXVideoRunner",
        "description": "High-fidelity real-time cinematic video generation."
    },
    "ltx-2.3": {
        "name": "Lightricks LTX-Video 2.3",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Lightricks/LTX-Video-2.3",
        "size_gb": 9.2,
        "vram_min_gb": 8,
        "vram_recommended_gb": 16,
        "runner_class": "inference.video.ltx.LTXVideoRunner",
        "description": "High-fidelity cinematic real-time open-source video generator with ComfyUI support."
    },
    "ovi": {
        "name": "Ovi Open-Video-Intelligence 7B",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Ovi-AI/Ovi-7B",
        "size_gb": 14.0,
        "vram_min_gb": 8,
        "vram_recommended_gb": 16,
        "runner_class": "inference.video.wan.WanT2VRunner",
        "description": "Native ComfyUI supported multi-resolution open video generation model."
    },
    "wan-2.1": {
        "name": "Wan2.1 Multi-Resolution Open Video Model",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Wan-AI/Wan2.1-T2V-14B-Diffusers",
        "size_gb": 28.0,
        "vram_min_gb": 8,
        "vram_recommended_gb": 24,
        "runner_class": "inference.video.wan.WanT2VRunner",
        "description": "Wan 2.1 SOTA open video model with native ComfyUI workflow support."
    },
    "wan-2.2": {
        "name": "Wan2.2 Enhanced High-Fidelity Video Engine",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "Wan-AI/Wan2.2-T2V-14B-Diffusers",
        "size_gb": 29.5,
        "vram_min_gb": 8,
        "vram_recommended_gb": 24,
        "runner_class": "inference.video.wan.WanT2VRunner",
        "description": "Wan 2.2 SOTA video generation model with enhanced inference quality and motion consistency."
    },
    "veo-2-4k": {
        "name": "Google Veo 2 4K (Community Cluster / API)",
        "category": "video",
        "subcategory": "text-to-video",
        "hf_repo": "google/veo-2-4k-community",
        "size_gb": 120.0,
        "vram_min_gb": 24,
        "vram_recommended_gb": 80,
        "runner_class": "inference.video.veo.VeoRunner",
        "description": "World-class SOTA 4K video generator. Defaults to Community Compute offloading on consumer hardware."
    },
    "llama-3.2-1b-instruct": {
        "name": "Llama 3.2 1B Instruct (AI Director)",
        "category": "text-generation",
        "subcategory": "llm-director",
        "hf_repo": "meta-llama/Llama-3.2-1B-Instruct",
        "size_gb": 2.5,
        "vram_min_gb": 2,
        "vram_recommended_gb": 4,
        "runner_class": "inference.llm_director.LLMDirectorRunner",
        "description": "Local AI Director for automatically enhancing prompts with VFX, motion, and 3D graphics."
    }
}
